name: Scrape latest jobs

on:
  push:
  workflow_dispatch:
  schedule:
  - cron: '0 */4 * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Set up Chrome WebDriver
      run: |
        wget https://chromedriver.storage.googleapis.com/94.0.4606.41/chromedriver_linux64.zip
        unzip chromedriver_linux64.zip
        sudo mv chromedriver /usr/local/bin/
        sudo chmod +x /usr/local/bin/chromedriver
        sudo ln -s /usr/local/bin/chromedriver /usr/bin/chromedriver
        rm chromedriver_linux64.zip
    - name: Run the script
      run: python scratchpad.py
    - name: Parse UniqueJobsdataMasterFile.json into table
      id: parse-json
      run: |
        echo "| Job Title | Job Location | Job Link | Job Posted |" > README.md
        echo "| --- | --- | --- | --- |" >> README.md
        jq -r '.[] | "| " + .job_title + " | " + .job_location + " | " + "[Apply](" + .JobLink + ")" + " | " + "$(date +'%e %B %Y')" + " |"' UniqueJobsdataMasterFile.json >> README.md
    - name: Commit and push if it changed
      run: |
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add README.md
        timestamp=$(date -u)
        git commit -m "Latest jobs: ${timestamp}" || exit 0
        git push
