name: Scrape latest jobs

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '0 */4 * * *'

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Check out this repo
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          sudo apt install -y chromium-browser

      - name: Run the script
        run: |
          python scratchpad.py || echo "Script failed, continuing workflow"

      - name: Parse ottacomdata.json into table
        id: parse-json
        run: |
          echo "| Job Title | Job Location | Job Link | Job Posted |" > README.md
          echo "| --- | --- | --- | --- |" >> README.md
          jq -r '.[] | "| " + .job_title + " | " + .job_location + " | " + "[Apply](" + .JobLink + ")" + " | " + "$(date +\"%e %B %Y\")" + " |"' ottacomdata.json >> README.md || echo "JSON parsing failed"

      - name: Set Git user credentials
        run: |
          git config user.name "Your Name"
          git config user.email "your-email@example.com"

      - name: Commit and push if it changed
        run: |
          git add README.md
          timestamp=$(date -u)
          git commit -m "Latest jobs: ${timestamp}" || exit 0
          git push
