name: Scrape latest jobs

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 */4 * * *'

jobs:
  ottacom:
    runs-on: ubuntu-latest

    steps:
      - name: Checking out repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install necessary packages
        run: |
          pip install requests beautifulsoup4 pandas webdriver-manager selenium

      - name: Run the scraping script
        run: python scratchpad.py || echo "Script failed, continuing workflow"

      - name: Set Git user credentials
        run: |
          git config --global user.name "Suresh Parimi"
          git config --global user.email "reachparimi@gmail.com"

      - name: Generate individual README files for each job
        run: |
          mkdir -p jobs
          echo "# Jobs from ottacom" > jobs/ottacom.md
          echo "| Job Title | Job Location | Job Link | Job Posted |" >> jobs/ottacom.md
          echo "| --- | --- | --- | --- |" >> jobs/ottacom.md
          while IFS="|" read -r job_title job_location job_link job_posted; do
            echo "| $job_title | $job_location | [Apply]($job_link) | $job_posted |" >> jobs/ottacom.md
          done < <(jq -r '.[] | "\(.position)|\(.location)|\(.description)|\(.post_date // (now | strftime("%e %B %Y %l:%M %p %Z")))"' existingjobs.json)

      - name: Update main README.md with links to job files
        run: |
          echo "# Latest Jobs" > README.md
          echo "" >> README.md
          echo "This page is updated at $(TZ='Asia/Kolkata' date +'%B %d, %Y %H:%M:%S')" >> README.md
          echo "" >> README.md
          echo "## Job Listings" >> README.md
          echo "" >> README.md
          echo "- [Jobs from ottacom](jobs/ottacom.md)" >> README.md
          echo "" >> README.md
          echo "## Table of Contents" >> README.md
          echo "" >> README.md
          echo "- [Jobs from ottacom](jobs/ottacom.md)" >> README.md

      - name: Set Git user credentials
        run: |
          git config --global user.name "Suresh Parimi"
          git config --global user.email "reachparimi@gmail.com"

      - name: Commit and push
        run: |
          git add README.md
          git add jobs
          timestamp=$(date -u)
          git commit -m "Latest jobs: ${timestamp}" || exit 0
          git push
