name: Scrape and Archive Jobs

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 */4 * * *'

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the repository
      - name: Checking out repo
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Setting up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      # Step 3: Install necessary packages
      - name: Installing necessary packages
        run: |
          apt list --installed
          sudo apt purge google-chrome-stable
          pip install chromedriver-autoinstaller selenium pyvirtualdisplay
          sudo apt-get install xvfb
          pip install requests beautifulsoup4 pandas webdriver-manager selenium

      # Step 4: Run the scraping script
      - name: Run the scraping script
        run: python scratchpad.py || echo "Script failed, continuing workflow"

  archive:
    runs-on: ubuntu-latest
    needs: scrape
    steps:
      # Step 1: Check out the repository
      - name: Checking out repo
        uses: actions/checkout@v3

      # Step 2: Create the archivedjobs.md file
      - name: Create archivedjobs.md
        run: |
          echo "| Job Title | Job Location | Job Link |" > archivedjobs.md
          echo "| --- | --- | --- |" >> archivedjobs.md
          jq -r '.[] | select(.job_title and .job_location and .JobLink) | "\(.job_title)|\(.job_location)|[Apply](\(.JobLink))"' masterdatabase.json | sed '/null/d' >> archivedjobs.md

      # Step 3: Set Git user credentials
      - name: Set Git user credentials
        run: |
          git config --global user.name "Suresh Parimi"
          git config --global user.email "reachparimi@gmail.com"

      # Step 4: Pull changes from the remote repository
      - name: Pull changes from remote repository
        run: git pull origin main

      # Step 5: Commit and push the changes to archivedjobs.md
      - name: Commit and push if it changed
        run: |
          git add archivedjobs.md
          timestamp=$(date -u)
          git commit -m "Archived jobs: ${timestamp}" || exit 0
          git push

  update_readme:
    runs-on: ubuntu-latest
    needs: archive
    steps:
      # Step 1: Check out the repository
      - name: Checking out repo
        uses: actions/checkout@v3

      # Step 2: Update main readme.md with archived jobs section
      - name: Update main readme.md with archived jobs section
        run: |
          sed -i '/^## Archived Jobs/d' README.md
          sed -i '/## Jobs posted in the past one week/a\## Archived Jobs\n\nYou can find the archived job listings here:\n\n[Archived Jobs](archivedjobs.md)' README.md

      # Step 3: Set Git user credentials
      - name: Set Git user credentials
        run: |
          git config --global user.name "Suresh Parimi"
          git config --global user.email "reachparimi@gmail.com"

      # Step 4: Commit and push the changes to readme.md
      - name: Commit and push if it changed
        run: |
          git add README.md
          timestamp=$(date -u)
          git commit -m "Update readme.md: ${timestamp}" || exit 0
          git push
