name: Scrape latest jobs

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 */4 * * *'

jobs:
  ottacom:
    runs-on: ubuntu-latest

    steps:
      - name: Checking out repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install necessary packages
        run: |
          pip install requests beautifulsoup4 pandas webdriver-manager selenium

      - name: Run the scraping script
        run: python scratchpad.py || echo "Script failed, continuing workflow"

      - name: Set Git user credentials
        run: |
          git config --global user.name "Suresh Parimi"
          git config --global user.email "reachparimi@gmail.com"

  relocatewithus:
    runs-on: ubuntu-latest

    steps:
      - name: Checking out repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4 pandas selenium

      - name: Run the scraping script
        run: python relocatewithus.py || echo "Script failed, continuing workflow"

      - name: Set Git user credentials
        run: |
          git config --global user.name "Suresh Parimi"
          git config --global user.email "reachparimi@gmail.com"

  combine-data:
    needs: [ottacom, relocatewithus]

    runs-on: ubuntu-latest

    steps:
      - name: Checking out repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install jsonlines

      - name: Combine data from ottacomdata.json and relocatewithusjobs.json
        run: |
          cat ottacomdata.json > existingjobs.json
          cat relocatewithusjobs.json > newjobs.json
          jq -s add existingjobs.json newjobs.json > alljobs.json

      - name: Update README.md from alljobs.json
        id: update-readme
        run: |
          git pull origin main
          cat README.md >> new_README.md
          echo "" >> new_README.md
          echo "# Latest Jobs" >> new_README.md
          echo "" >> new_README.md
          echo "This page is updated at $(TZ='Asia/Kolkata' date +'%B %d, %Y %H:%M:%S')" >> new_README.md
          echo "" >> new_README.md
          echo "| Job Title | Job Location | Job Link | Job Posted | Visa Sponsorship |" >> new_README.md
          echo "| --- | --- | --- | --- | --- |" >> new_README.md
          jq -r '.[] | "| \(.position) | \(.location) | [Apply](\(.description)) | \(.post_date) | \(.visa) |"' alljobs.json >> new_README.md || echo "JSON parsing failed"
          mv new_README.md README.md

      - name: Set Git user credentials
        run: |
          git config --global user.name "Suresh Parimi"
          git config --global user.email "reachparimi@gmail.com"

      - name: Commit and push
        run: |
          git add README.md
          git add alljobs.json
          timestamp=$(date -u)
          git commit -m "Latest jobs: ${timestamp}" || exit 0
          git push
